import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./Components/Navbar";
import Sidebar from "./Components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main className="flex">
          <Sidebar />
          <div className="ml-[280px] mt-[80px] flex  w-[95%] border-2 border-[red] h-[100vh]">
            <aside className="basis-[70%]">{children}</aside>
            <aside className="basis-[30%] border-2 border-[green]"></aside>
          </div>
        </main>
      </body>
    </html>
  );
}
