import '../globals.css'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "../Components/Navbar";
import Sidebar from "../Components/Sidebar";
import Promotions from "../Components/Promotions";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="font-family-raleway">
      <body className={inter.className} >
        <Navbar />
        <main className="md:flex">
          <Sidebar />
          <div className="md:ml-[280px] md:mt-[80px] mb-[100px] flex max-sm:p-[1rem] md:w-[95%] overflow-hidden  height-minus-80">
            <aside className="md:w-[70%] h-full overflow-auto">{children}</aside>
            <aside className="w-[30%] hidden md:block">
              <Promotions />
            </aside>
          </div>
        </main>
      </body>
    </html>
  );
}
